name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python and Poetry
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run Linting
        run: |
          poetry run pylint src/
      - name: Run Tests
        run: |
          poetry run pytest
      - name: Wait for previous steps
        run: |
          wait
  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker compose build
  test-docker:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker container tests (pytest)
        run: |
          docker compose up -d
          docker exec -it boilerplate-app poetry run pytest
          docker compose down
